repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: https://github.com/grantjenks/blue
    rev: v0.9.1
    hooks:
      - id: blue

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args:
          - "--profile"
          - "blue"
        exclude: "^docs/.*$"

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.3.0 # Modify this to be the version you want
    hooks:
      - id: pydocstyle

  - repo: local
    hooks:
      - id: pip-audit
        name: pip-audit
        entry: pip-audit
        args: []
        language: system
        pass_filenames: false
        types: [python] # Opcional: se você quiser que isso seja executado apenas quando arquivos Python forem alterados.
